---
# tasks/main.yml

- name: (sys) update host apt cache
  apt:
    cache_valid_time: 3600
    update_cache: true

- name: (sys) install sys tools
  apt:
    install_recommends: false
    name: "{{ item }}"
    state: present
  loop:
    - tar
    - curl

- name: (sys) create traefik system group
  group:
    name: "traefik"
    system: "true"
    state: present

- name: (sys) create traefik system user
  user:
    createhome: "false"
    group: "traefik"
    home: "/etc/traefik"
    name: "traefik"
    shell: "/usr/sbin/nologin"
    system: "true"

- name: (sys) download traefik sources
  get_url:
    url: "https://github.com/traefik/traefik/releases/download/v{{ traefik_version }}/traefik_v{{ traefik_version }}_linux_amd64.tar.gz"
    dest: "/tmp/traefik_{{ traefik_version }}.tar.gz"
  register: traefik_source

- name: (sys) unpack traefik sources
  unarchive:
    copy: false
    dest: "/tmp/"
    src: "{{ traefik_source.dest }}"
  register: traefik_source_unpack

- name: (sys) copy binary to system
  copy:
    dest: "/usr/bin/traefik"
    group: "traefik"
    mode: 0755
    owner: "traefik"
    remote_src: true
    src: "/tmp/traefik"

- name: (sys) create needed folder for traefik
  file:
    group: "traefik"
    mode: 0755
    owner: "traefik"
    path: "{{ item }}"
    state: directory
  loop:
    - "/etc/traefik"
    - "/etc/traefik/dynamic"

- name: (sys) look if logs file for traefik exists
  command: "ls /var/log/traefik.log"
  register: logsfile
  changed_when: "'No such file' in logsfile.stderr"
  ignore_errors: true

- name: (sys) create logs file for traefik if needed
  file:
    group: "traefik"
    mode: 0644
    owner: "traefik"
    path: "/var/log/traefik.log"
    state: touch
  when: logsfile is changed

- name: (sys) look if acme file for traefik exists
  command: "ls /etc/traefik/acme.json"
  register: acmefile
  changed_when: "'No such file' in acmefile.stderr"
  ignore_errors: true

- name: (sys) create acme file for traefik if needed
  file:
    group: "traefik"
    mode: 600
    owner: "traefik"
    path: "/etc/traefik/acme.json"
    state: touch
  when: acmefile is changed

- name: (sys) installing traefik configuration file
  template:
    dest: "/etc/traefik/traefik.yml"
    group: "traefik"
    mode: u+rw,g-wx,o-wx
    owner: "traefik"
    src: "templates/traefik.yml.j2"

- name: (sys) installing systemd unit
  template:
    dest: "/lib/systemd/system/traefik.service"
    group: "root"
    mode: 0644
    owner: "root"
    src: "templates/traefik.service.j2"

- name: (sys) start traefik
  systemd:
    daemon_reload: true
    masked: false
    name: traefik
    state: started
