---

dependency:
  name: galaxy

driver:
  name: vagrant
  provider:
    name: virtualbox

lint: |
  set -e .
  yamllint .
  ansible-lint

platforms:
  - name: traefik-ubuntu
    box: ubuntu/focal64
  - name: traefik-debian
    box: debian/buster64
  - name: traefik-debian11
    box: debian/bullseye64

provisioner:
  name: ansible
  lint:
    name: ansible-lint

scenario:
  name: default

verifier:
  name: ansible
