---

- name: Verify
  become: true
  hosts: all
  tasks:
  - name: (check) Test if services are started and enabled
    systemd:
      enabled: true
      masked: false
      name: "traefik"
      state: started

  - name: (check) Test if services ports are open and reachable
    wait_for:
      port: "{{ item }}"
    loop:
      - 80
      - 443
      - 8080

  - name: (check) Test if Traefik web interface (dashboard) is OK
    uri:
      url: "http://localhost:8080/dashboard"
      status_code: 200
