---

- name: Verify
  hosts: all
  tasks:
  - name: (check) Test if services are started and enabled
    shell: "systemctl status traefik.service"
    changed_when: false

  - name: (check) Test if services ports are open and reachable
    shell: "ss -ntlp | grep {{ item }}"
    loop:
      - 80
      - 443
      - 8080
    changed_when: false

  - name: (check) Test if Traefik web interface (dashboard) is OK
    uri:
      url: "http://localhost:8080/dashboard"
      status_code: 200
